plugins {
    id 'com.android.library' version '8.13.0' apply false
}

group 'io.flutterfastkit.fk_user_agent'

version '2.0.0'

apply plugin: 'com.android.library'

android {
    namespace 'io.flutterfastkit.fk_user_agent'

    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 16
    }

    lint {
        disable 'InvalidPackage'
    }
}
